insert into customer (id, name, phone_number, is_delete) values ('c-123', 'Joko', '1234567', false);
insert into employee (id, name, is_delete) values ('e-123', 'Maell', false);
insert into employee (id, name, is_delete) values ('e-124', 'Lee', false);
insert into employee (id, name, is_delete) values ('e-125', 'Jution', false);
insert into employee (id, name, is_delete) values ('e-126', 'Dadi', false);
insert into employee (id, name, is_delete) values ('e-127', 'Bagus', false);
insert into uom (id, name, is_delete) values ('123', 'Kg', false);
insert into uom (id, name, is_delete) values ('456', 'Gr', false);
insert into uom (id, name, is_delete) values ('789', 'Lt', false);
insert into product (id, name, price, uom_id, is_delete) values ('p-220', 'Cuci', 4500, '123', false);
insert into product (id, name, price, uom_id, is_delete) values ('p-221', 'Cuci + Setrika', 7000, '123', false);
insert into product (id, name, price, uom_id, is_delete) values ('p-222', 'Setrika', 3000, '123', false);